name: PERFORMANCECAFFEINE
favicon: null
layout_spectrum: 0.2567353001795709
typography_spectrum: 0.31140329223126173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.30876503023318946
  lightness: 0.0874921556096524
  saturation: 0.5832418056670576
  rhythmicContrast: 0.5085027273744345
purpose: []
