name: PERFORMANCECAFFEINE
favicon: null
layout_spectrum: 0.53888
typography_spectrum: 0.35147
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#339acc'
    - '#d1d0d2'
    - '#1f607f'
  brandStrength: 0.5
  lightness: 0.0874921556096524
  saturation: 0.5832418056670576
  rhythmicContrast: 0.5085027273744345
purpose: []
